#!/bin/sh
#
# Early Detection Research Network (EDRN) Informatics Center (IC)
# Cancer Data Expo
#
# Starts & stops the Cancer Data Expo Supervisor, which in turn monitors and
# controls all of the processes necessary to run the Cancer Data Expo
#
# chkconfig: 345 87 12
# description: Cancer Data Expo

home="${buildout:directory}"
bin="${dollar}{home}/bin"
supervisord="${dollar}{bin}/supervisord"
supervisorctl="${dollar}{bin}/supervisorctl"

case "${dollar}1" in
start)
        echo "Starting Cancer Data Expo"
        "${dollar}supervisord"
        ;;
stop)
        echo "Stopping Cancer Data Expo"
        "${dollar}supervisorctl" shutdown
        ;;
restart)
        echo "Restarting Cancer Data Expo"
        "${dollar}supervisorctl" shutdown
        /bin/sleep 5
        "${dollar}supervisord"
        ;;
graceful)
        echo "Restarting Cancer Data Expo processes under existing Supervisor"
        "${dollar}supervisorctl" restart all
        ;;
status)
        "${dollar}supervisorctl" status
        ;;
*)
        echo "Usage: ${dollar}0 {start|stop|restart|graceful|status}" 1>&2
        ;;
esac
exit 0
