#!/bin/sh
#
# update-rdf - Update EDRN's various RDF data sources from the DMCC
#
# Note that templates/update-rdf generates bin/update-rdf.  Are you editing
# the right file?
#
# Copyright 2012 California Institute of Technology. ALL RIGHTS
# RESERVED. U.S. Government Sponsorship acknowledged.

PATH=/usr/local/bin:/usr/bin:/bin
export PATH

credential='${zope:username}:${zope:password}'

exec curl \
    --location \
    --output /dev/null \
    --silent \
    --show-error \
    --user "$credential" \
    http://${interfaces:zope}:${ports:zope}/dmcc/@@updateRDF


