#!/bin/sh
#
# update-summary - Update EDRN's various RDF data sources for the Caner Data Expo
#
# Note that templates/update-summary generates bin/update-summary.  Are you editing
# the right file?
#
# Copyright 2012–2016 California Institute of Technology. ALL RIGHTS
# RESERVED. U.S. Government Sponsorship acknowledged.

PATH=/usr/local/bin:/usr/bin:/bin
export PATH

credential='${zope:username}:${zope:password}'

exec curl \
    --location \
    --output /dev/null \
    --silent \
    --show-error \
    --user "$credential" \
    http://${interfaces:zope}:${ports:zope}/cancerdataexpo/@@updateSummary


