# EDRN Cancer Data Expo Imaging
# =============================
#

---

name: EDRN Cancer Data Expo Imaging


# Triggers
# --------
#
# Run on any push to the Renaissance branch of the P5 code.

on:
    push:
        branches:
            -   master
        paths:
            -   'src/**'
            -   'etc/**'
            -   'Dockerfile'
            -   'site.cfg'


# Jobs
# ----
#
# What to do.

jobs:
    imaging:
        name: 🏞 CancerDataExpo Imaging
        runs-on: ubuntu-latest
        steps:
            -
                name: 💳 Docker Hub Identification
                uses: docker/login-action@v2
                with:
                    username: ${{secrets.DOCKERHUB_USERNAME}}
                    password: ${{secrets.DOCKERHUB_TOKEN}}
            -
                name: 📚 Repository Checkout
                uses: actions/checkout@v3
            -
                name: 🎰 QEMU Multiple Machine Emulation
                uses: docker/setup-qemu-action@v2
            -
                name: 🚢 Docker Buildx
                uses: docker/setup-buildx-action@v2
            -
                name: 🧱 Image Construction and Publication
                uses: docker/build-push-action@v3
                with:
                    context: .
                    file: Dockerfile
                    platforms: linux/amd64,linux/arm64/v8
                    push: true
                    tags: ${{secrets.DOCKERHUB_USERNAME}}/cancerdataexpo:latest

...


# -*- mode: YAML; tab-width: 4 -*-
